# Site settings
title: 'Crimes Against Computers' # Your Title
tagline: "Joseph pallamidessi's personal blog" # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: kramdown 
highlighter: rouge
baseurl:  # the subpath of your site, e.g. /blog/
permalink: :year/:month/:day/:title
imagesurl: "/images/"
thumbsurl: "/images/thumbnail/"
